### ISSUE TITLE
module buffer from Node standard library

### ISSUE THREAD

**Issue by thomaslc66** [taoqf/MQTT.js#1]
![image](https://user-images.githubusercontent.com/9827392/59552532-8919bb80-8f88-11e9-882c-8130f2437733.png)

**Comment by taoqf** [comment]
What about 3.0.4?
I did not get this error, may be I had `buffer` in my project's dependencies already.

**Comment by taoqf** [comment]
@thomaslc66 Could you please retest?

**Comment by taoqf** [comment]
I will close this issue for now, reopen it when you still can not make it work.
