### ISSUE TITLE
Android and Ios linking

### ISSUE THREAD

**Issue by thomaslc66** [taoqf/MQTT.js#2]
Is it possible for you to add more info about the linking process on the readme as well as with kind of data the message type supports ?? Thank you very much

https://github.com/SudoPlz/sp-react-native-mqtt/pull/1#issuecomment-498517526

**Comment by taoqf** [comment]
Sorry I don't get you.
It is a pure js mobule so you could use it just like [mqtt.js](https://www.npmjs.com/package/mqtt).
You don't need react link this module or do something like that.
Just require and use it will be fine.

**Comment by thomaslc66** [comment]
I tell you this because when you add your lib on a react native and run it.
We got an error : 
![image](https://user-images.githubusercontent.com/9827392/63224827-13b9a980-c1ca-11e9-9cb2-40a7e967e289.png)

should maybe add all dependencies in the package.json.

**Comment by taoqf** [comment]
Make sure you use [@taoqf/react-native-mqtt](https://www.npmjs.com/package/@taoqf/react-native-mqtt), not just use [mqtt.js](https://www.npmjs.com/package/mqtt) directly, please.
