### ISSUE TITLE
TLS auth with certificates doesn't work

### ISSUE THREAD

**Issue by FrozenPyrozen** [taoqf/MQTT.js#6]
@taoqf I can't connect to mqtt broker with tls( Also I've seen that you removed 'tls' file  in https://github.com/taoqf/MQTT.js/commit/24d8c0fae0e68dd81be3c33b15580bbe8091191f. Can you propose or help to find solution with it?

**Comment by taoqf** [comment]
Sorry for that, I could not help you out. because I don't know that much. I removed them because I hope we could use websocket for communication as the only way.that would make things easier, I think.

**Comment by FrozenPyrozen** [comment]
@taoqf thank you for answer, you make a great job anyway💪

**Comment by FrozenPyrozen** [comment]
@taoqf can we use secure websocket connection with certificates through wss with that lib?

**Comment by taoqf** [comment]
Yes, I think.

**Comment by taoqf** [comment]
with wss:xxx
